# Generated by Django 5.0.6 on 2024-07-12 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='skills',
            new_name='teacher_resume',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='date_of_birth',
        ),
    ]
