# Generated by Django 5.0.6 on 2024-07-16 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_trainer', models.CharField(max_length=20)),
                ('class_prefect', models.CharField(max_length=20)),
                ('number_of_laptops', models.IntegerField(default=0)),
                ('color_of_chairs', models.CharField(default='DefaultColor', max_length=255)),
                ('number_of_chairs', models.PositiveSmallIntegerField(default=0)),
                ('number_of_tables', models.PositiveSmallIntegerField(default=0)),
                ('number_of_boards', models.PositiveSmallIntegerField(default=0)),
                ('number_of_students', models.IntegerField(default=0)),
                ('number_of_windows', models.PositiveSmallIntegerField(default=0)),
                ('number_of_trainers', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
