# Generated by Django 5.0.6 on 2024-07-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='educational_resources',
            new_name='class_prefect',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='sufficient_space',
            new_name='class_trainer',
        ),
        migrations.RemoveField(
            model_name='class',
            name='board',
        ),
        migrations.RemoveField(
            model_name='class',
            name='chairs',
        ),
        migrations.RemoveField(
            model_name='class',
            name='learning_models',
        ),
        migrations.RemoveField(
            model_name='class',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='class',
            name='students',
        ),
        migrations.RemoveField(
            model_name='class',
            name='tables',
        ),
        migrations.RemoveField(
            model_name='class',
            name='trainers',
        ),
        migrations.RemoveField(
            model_name='class',
            name='windows',
        ),
        migrations.AddField(
            model_name='class',
            name='color_of_chairs',
            field=models.CharField(default='DefaultColor', max_length=255),
        ),
        migrations.AddField(
            model_name='class',
            name='number_of_boards',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='class',
            name='number_of_chairs',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='class',
            name='number_of_laptops',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='class',
            name='number_of_students',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='class',
            name='number_of_tables',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='class',
            name='number_of_trainers',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='class',
            name='number_of_windows',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
