# Generated by Django 5.0.6 on 2024-06-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('code', models.PositiveSmallIntegerField()),
                ('learning_objective', models.CharField(max_length=20)),
                ('teaching_method', models.CharField(max_length=20)),
                ('career_outcome', models.CharField(max_length=20)),
                ('course_materials', models.PositiveSmallIntegerField()),
                ('assessments', models.CharField(max_length=10)),
                ('practical_application', models.CharField(max_length=20)),
                ('clear_description', models.CharField(max_length=20)),
                ('course_period', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
